# Generated by Django 6.0.4 on 2026-05-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url_name',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
    ]
