# Generated by Django 6.0.4 on 2026-05-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='url_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
