# Generated by Django 6.0.4 on 2026-05-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_service_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='url_name',
            field=models.CharField(blank=True, default='', max_length=150),
            preserve_default=False,
        ),
    ]
