# Generated by Copilot on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_mediapanel"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="status_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]